<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>JeroBackpack</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <Version>3.0.0</Version>
        <OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="SPT.Server">
            <HintPath>$(SptRoot)\SPT.Server.dll</HintPath>
        </Reference>
        <Reference Include="SPTarkov.Common">
            <HintPath>$(SptRoot)\SPTarkov.Common.dll</HintPath>
        </Reference>
        <Reference Include="SPTarkov.DI">
            <HintPath>$(SptRoot)\SPTarkov.DI.dll</HintPath>
        </Reference>
        <Reference Include="SPTarkov.Server.Core">
            <HintPath>$(SptRoot)\SPTarkov.Server.Core.dll</HintPath>
        </Reference>
        <Reference Include="SPTarkov.Reflection">
            <HintPath>$(SptRoot)\SPTarkov.Reflection.dll</HintPath>
        </Reference>
        <Reference Include="SemanticVersioning">
            <HintPath>$(SptRoot)\SemanticVersioning.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>